name: "Build master"
on:
  pull_request:
jobs:
  check_files:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      output1: ${{ steps.set_files_changed.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Set vars
        id: set_files_changed
        run: |
          ./check_file_changed.py
  second:
    needs:   check_files
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Echo one
        run: |
          echo "22"
  third:
    needs:   check_files
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{needs.job1.outputs.output1}} == "true"
    steps:
      - name: Echo one
        run: |
          echo "33"

  subjob1:
    uses: ./.github/workflows/_subjob.yml
  subjob2:
    if: ${{needs.job1.outputs.output1}} == "true"
    uses: ./.github/workflows/_subjob.yml
