name: "Build master"
on:
  pull_request:
jobs:
  check_files:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      output1: ${{ steps.set_files_changed.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Set vars
        id: set_files_changed
        run: |
          python ./check_file_changed.py
      - run: |
          echo $GITHUB_OUTPUT
  second:
    needs:   check_files
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git show HEAD
      - run: git show HEAD^1
      - name: 'Get a list of changed files to process'
        run: git diff-tree --name-only -r HEAD^1 HEAD
  third:
    needs:   check_files
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ needs.check_files.outputs.output1 == true }}
    steps:
      - run: |
          echo "33"
  subjob1:
    needs:   check_files
    uses: ./.github/workflows/_subjob.yml
  subjob2:
    needs:   check_files
    if: ${{ needs.check_files.outputs.output1 == true }}
    uses: ./.github/workflows/_subjob.yml
  subjob3:
    needs: check_files
    if: ${{ false }}
    uses: ./.github/workflows/_subjob.yml
