name: "Build PR"
on:
  push
jobs:
  sample:
    name: Discord Webhook Notify
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          title: GitHub build
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "**Build Failed** [build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          color: 0xff0000
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}